#! /usr/bin/env ruby

require "pg"

CONNECTION = PG.connect(dbname: "expenses")

def display_help 
  puts <<~HELP
    An expense recording system

    Commands:

    add AMOUNT MEMO - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP
end

def list 
  result = CONNECTION.exec("SELECT * FROM expenses ORDER BY created_on;")

  result.each do |tuple|
    columns = [ tuple["id"].rjust(3),
                tuple["created_on"].rjust(10),
                tuple["amount"].rjust(10),
                tuple["memo"] ]
              
    puts columns.join(" | ")
  end
end

def add_expense(args)
  amount = args[0]
  memo = args[1..-1].join(" ")

  if ARGV.size <= 2 
    abort "Argument missing: you must provide both an amount and a memo note"
  else
    sql = ("INSERT INTO expenses(amount, memo, created_on)
            VALUES (#{amount}, '#{memo}', DEFAULT);")
    CONNECTION.exec(sql)
    puts "\"#{memo}\" added to expenses."
  end
end


case ARGV[0]
when 'list' then list
when 'add' then add_expense(ARGV[1..-1])
else display_help
end